import { IconType } from "react-icons";
import {
  SiC,
  SiClojure,
  SiCplusplus,
  SiCss3,
  SiDart,
  SiDocker,
  SiElixir,
  SiGnubash,
  SiGo,
  SiGraphql,
  SiHaskell,
  SiHtml5,
  SiJavascript,
  SiJson,
  SiKotlin,
  SiLua,
  SiMarkdown,
  SiPerl,
  SiPhp,
  SiPython,
  SiReact,
  SiRuby,
  SiRust,
  SiSass,
  SiScala,
  SiSvelte,
  SiSwift,
  SiToml,
  SiTypescript,
  SiVuedotjs,
  SiYaml,
} from "react-icons/si";
import {
  VscDatabase,
  VscEdit,
  VscFile,
  VscFileBinary,
  VscFileCode,
  VscFileMedia,
  VscFilePdf,
  VscFileZip,
  VscFolder,
  VscGear,
  VscKey,
  VscLock,
} from "react-icons/vsc";

export type IconSpec = { icon: IconType; color: string };

// A colored logo per known extension; falls back to a generic-but-typed icon
// (media / pdf / archive / binary / code) so nearly every file gets something.
const MAP: Record<string, IconSpec> = {
  // web + scripting
  ts: { icon: SiTypescript, color: "#3178c6" },
  mts: { icon: SiTypescript, color: "#3178c6" },
  cts: { icon: SiTypescript, color: "#3178c6" },
  tsx: { icon: SiReact, color: "#61dafb" },
  js: { icon: SiJavascript, color: "#f7df1e" },
  jsx: { icon: SiReact, color: "#61dafb" },
  mjs: { icon: SiJavascript, color: "#f7df1e" },
  cjs: { icon: SiJavascript, color: "#f7df1e" },
  py: { icon: SiPython, color: "#4b8bbe" },
  pyw: { icon: SiPython, color: "#4b8bbe" },
  rb: { icon: SiRuby, color: "#cc342d" },
  php: { icon: SiPhp, color: "#8892bf" },
  html: { icon: SiHtml5, color: "#e34f26" },
  htm: { icon: SiHtml5, color: "#e34f26" },
  css: { icon: SiCss3, color: "#2965f1" },
  scss: { icon: SiSass, color: "#cc6699" },
  sass: { icon: SiSass, color: "#cc6699" },
  vue: { icon: SiVuedotjs, color: "#42b883" },
  svelte: { icon: SiSvelte, color: "#ff3e00" },
  // systems / compiled
  rs: { icon: SiRust, color: "#dea584" },
  go: { icon: SiGo, color: "#00add8" },
  c: { icon: SiC, color: "#a8b9cc" },
  h: { icon: SiC, color: "#a8b9cc" },
  cpp: { icon: SiCplusplus, color: "#00599c" },
  cc: { icon: SiCplusplus, color: "#00599c" },
  cxx: { icon: SiCplusplus, color: "#00599c" },
  hpp: { icon: SiCplusplus, color: "#00599c" },
  java: { icon: VscFileCode, color: "#e76f00" },
  kt: { icon: SiKotlin, color: "#7f52ff" },
  kts: { icon: SiKotlin, color: "#7f52ff" },
  swift: { icon: SiSwift, color: "#f05138" },
  dart: { icon: SiDart, color: "#0175c2" },
  cs: { icon: VscFileCode, color: "#9b4f96" },
  scala: { icon: SiScala, color: "#dc322f" },
  clj: { icon: SiClojure, color: "#5881d8" },
  cljs: { icon: SiClojure, color: "#5881d8" },
  ex: { icon: SiElixir, color: "#7c608a" },
  exs: { icon: SiElixir, color: "#7c608a" },
  hs: { icon: SiHaskell, color: "#5e5086" },
  pl: { icon: SiPerl, color: "#39457e" },
  pm: { icon: SiPerl, color: "#39457e" },
  lua: { icon: SiLua, color: "#5b7ec7" },
  // shell + config + data
  sh: { icon: SiGnubash, color: "#4eaa25" },
  bash: { icon: SiGnubash, color: "#4eaa25" },
  zsh: { icon: SiGnubash, color: "#4eaa25" },
  fish: { icon: SiGnubash, color: "#4eaa25" },
  md: { icon: SiMarkdown, color: "#9aa7b6" },
  markdown: { icon: SiMarkdown, color: "#9aa7b6" },
  // Whiteboard scenes (Excalidraw)
  board: { icon: VscEdit, color: "#6965db" },
  json: { icon: SiJson, color: "#cbcb41" },
  jsonc: { icon: SiJson, color: "#cbcb41" },
  yml: { icon: SiYaml, color: "#cb171e" },
  yaml: { icon: SiYaml, color: "#cb171e" },
  toml: { icon: SiToml, color: "#9c6b3f" },
  xml: { icon: VscFileCode, color: "#e37933" },
  graphql: { icon: SiGraphql, color: "#e10098" },
  gql: { icon: SiGraphql, color: "#e10098" },
  proto: { icon: VscFileCode, color: "#7aa2f7" },
  ini: { icon: VscGear, color: "#8b93a7" },
  cfg: { icon: VscGear, color: "#8b93a7" },
  conf: { icon: VscGear, color: "#8b93a7" },
  env: { icon: VscGear, color: "#dccf4b" },
  properties: { icon: VscGear, color: "#8b93a7" },
  // databases
  sql: { icon: VscDatabase, color: "#7aa2f7" },
  sqlite: { icon: VscDatabase, color: "#7aa2f7" },
  db: { icon: VscDatabase, color: "#7aa2f7" },
  // images / media
  png: { icon: VscFileMedia, color: "#b180d7" },
  jpg: { icon: VscFileMedia, color: "#b180d7" },
  jpeg: { icon: VscFileMedia, color: "#b180d7" },
  gif: { icon: VscFileMedia, color: "#b180d7" },
  bmp: { icon: VscFileMedia, color: "#b180d7" },
  webp: { icon: VscFileMedia, color: "#b180d7" },
  avif: { icon: VscFileMedia, color: "#b180d7" },
  ico: { icon: VscFileMedia, color: "#b180d7" },
  tiff: { icon: VscFileMedia, color: "#b180d7" },
  svg: { icon: VscFileMedia, color: "#ffb13b" },
  mp4: { icon: VscFileMedia, color: "#f16d6d" },
  mov: { icon: VscFileMedia, color: "#f16d6d" },
  webm: { icon: VscFileMedia, color: "#f16d6d" },
  mp3: { icon: VscFileMedia, color: "#5db075" },
  wav: { icon: VscFileMedia, color: "#5db075" },
  // documents
  pdf: { icon: VscFilePdf, color: "#e5472d" },
  doc: { icon: VscFileCode, color: "#2b7cd3" },
  docx: { icon: VscFileCode, color: "#2b7cd3" },
  odt: { icon: VscFileCode, color: "#2b7cd3" },
  rtf: { icon: VscFileCode, color: "#2b7cd3" },
  xls: { icon: VscFileCode, color: "#1d9b5e" },
  xlsx: { icon: VscFileCode, color: "#1d9b5e" },
  csv: { icon: VscFileCode, color: "#1d9b5e" },
  ppt: { icon: VscFileCode, color: "#d24726" },
  pptx: { icon: VscFileCode, color: "#d24726" },
  txt: { icon: VscFile, color: "#9aa7b6" },
  log: { icon: VscFile, color: "#8b93a7" },
  // archives
  zip: { icon: VscFileZip, color: "#c6923e" },
  tar: { icon: VscFileZip, color: "#c6923e" },
  gz: { icon: VscFileZip, color: "#c6923e" },
  tgz: { icon: VscFileZip, color: "#c6923e" },
  rar: { icon: VscFileZip, color: "#c6923e" },
  "7z": { icon: VscFileZip, color: "#c6923e" },
  bz2: { icon: VscFileZip, color: "#c6923e" },
  xz: { icon: VscFileZip, color: "#c6923e" },
  // executables / binaries
  exe: { icon: VscFileBinary, color: "#8fbf7f" },
  msi: { icon: VscFileBinary, color: "#8fbf7f" },
  dll: { icon: VscFileBinary, color: "#8b8b93" },
  so: { icon: VscFileBinary, color: "#8b8b93" },
  dylib: { icon: VscFileBinary, color: "#8b8b93" },
  bin: { icon: VscFileBinary, color: "#8b8b93" },
  wasm: { icon: VscFileBinary, color: "#654ff0" },
  class: { icon: VscFileBinary, color: "#8b8b93" },
  o: { icon: VscFileBinary, color: "#8b8b93" },
  // keys / secrets
  pem: { icon: VscKey, color: "#dccf4b" },
  key: { icon: VscKey, color: "#dccf4b" },
  crt: { icon: VscLock, color: "#5db075" },
  cert: { icon: VscLock, color: "#5db075" },
};

// Whole-filename matches (no extension, or special files).
const NAMES: Record<string, IconSpec> = {
  dockerfile: { icon: SiDocker, color: "#2496ed" },
  ".gitignore": { icon: VscGear, color: "#f05032" },
  ".gitattributes": { icon: VscGear, color: "#f05032" },
  ".dockerignore": { icon: SiDocker, color: "#2496ed" },
  makefile: { icon: VscGear, color: "#8b93a7" },
  license: { icon: VscFile, color: "#d4b13a" },
  ".env": { icon: VscGear, color: "#dccf4b" },
};

/** Material-icon-theme style: a colored logo per file type. */
export function fileIcon(path: string): IconSpec {
  const name = (path.split("/").pop() ?? "").toLowerCase();
  if (NAMES[name]) return NAMES[name];
  const ext = name.includes(".") ? name.split(".").pop()! : "";
  return MAP[ext] ?? { icon: VscFile, color: "#8b8b93" };
}

// Folders stay folder-shaped; well-known names just get a distinct tint.
const FOLDER_COLORS: Record<string, string> = {
  ".vscode": "#3a9fd8",
  ".github": "#8b949e",
  ".git": "#f05032",
  node_modules: "#cb3837",
  src: "#6b93d6",
  lib: "#6b93d6",
  dist: "#8b93a7",
  build: "#8b93a7",
  out: "#8b93a7",
  target: "#8b93a7",
  public: "#dd8a3c",
  static: "#dd8a3c",
  assets: "#dd8a3c",
  images: "#dd8a3c",
  docs: "#4b8bbe",
  documentation: "#4b8bbe",
  test: "#cc8f3a",
  tests: "#cc8f3a",
  __tests__: "#cc8f3a",
  spec: "#cc8f3a",
  migrations: "#7aa2f7",
  db: "#7aa2f7",
  database: "#7aa2f7",
  api: "#8fbf7f",
  server: "#8fbf7f",
  backend: "#8fbf7f",
  config: "#8b93a7",
  ".config": "#8b93a7",
  deploy: "#ff7b72",
  scripts: "#4eaa25",
};

/** Folder-shaped icon, tinted by well-known name (else default amber). */
export function folderIcon(name: string): IconSpec {
  return { icon: VscFolder, color: FOLDER_COLORS[name.toLowerCase()] ?? "#c6923e" };
}
